#persistence volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 50Gi
#  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # pode gravar, pode ler desde que esteja no mesmo NODE
    # - ReadWriteMany 
  # persistentVolumeReclaimPolicy: Recycle
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
