apiVersion: v1
kind: Secret
metadata:
  name: goserver-secret
type: Opaque
data:
  USER: Z2Ficwo=
  PASSWORD: MTIzNDU2Cg==
  #base64, nao siginifica que esta seguro, mas é o padrao do k8s, da pra integrar com sistema de segunraças 